name: Generate API Documentation

on:
  push:
    branches: [ main ]
    paths:
      - 'terraform/modules/api/api.yml'
  workflow_dispatch:

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Create docs directory
        run: mkdir -p public

      - name: Install Redocly
        run: npm install -g @redocly/cli

      - name: Generate HTML documentation
        run: |
          npx @redocly/cli build-docs terraform/modules/api/api.yml \
            --output public/index.html \
            --title "API Documentation"

      - name: Copy OpenAPI spec
        run: cp terraform/modules/api/api.yml public/openapi.yml

      - name: Create .nojekyll
        run: touch public/.nojekyll

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public
          branch: gh-pages
          clean: true
          single-commit: true